#ifndef CLIMITS_H
#define CLIMITS_H

// c99 5.2.4.1 translation limits
#define CMAX_BLOCK_NESTING 128
#define CMAX_CONDITIONAL_INCLUDES 63
#define CMAX_PAREN_DECLARATORS 63
#define CMAX_PAREN_EXP 63
#define CMAX_INTERNAL_ID_CHARS 63
#define CMAX_EXTERNAL_ID_CHARS 31
#define CMAX_EXTERNAL_ID 4095
#define CMAX_BLOCK_ID 511
#define CMAX_MACRO_ID 4095
#define CMAX_FUNC_PARAMS 127
#define CMAX_MACRO_PARAMS 127
#define CMAX_LINE_LENGTH 4095
#define CMAX_STRLEN 4095
#define CMAX_OBJSIZE 65535
#define CMAX_INCLUDE_NESTING 15
#define CMAX_CASE_LABELS 1023
#define CMAX_STRUCT_MEMBERS 1023
#define CMAX_UNION_MEMBERS 1023
#define CMAX_ENUM_CONSTANTS 1023
#define CMAX_NESTED_STRUCTS 63
#define CMAX_PUNCTUATOR_LENGTH 3

#endif // !CLIMITS_H
