#ifndef C_LIMITS_H
#define C_LIMITS_H

// c99 5.2.4.1 translation limits
#define C_MAX_BLOCK_NESTING 128
#define C_MAX_CONDITIONAL_INCLUDES 63
#define C_MAX_PAREN_DECLARATORS 63
#define C_MAX_PAREN_EXPR 63
#define C_MAX_INTERNAL_ID_CHARS 63
#define C_MAX_EXTERNAL_ID_CHARS 31
#define C_MAX_EXTERNAL_ID 4095
#define C_MAX_BLOCK_ID 511
#define C_MAX_MACRO_ID 4095
#define C_MAX_FUNC_PARAMS 127
#define C_MAX_MACRO_PARAMS 127
#define C_MAX_LINE_LENGTH 4095
#define C_MAX_STRLEN 4095
#define C_MAX_OBJSIZE 65535
#define C_MAX_INCLUDE_NESTING 15
#define C_MAX_CASE_LABELS 1023
#define C_MAX_STRUCT_MEMBERS 1023
#define C_MAX_UNION_MEMBERS 1023
#define C_MAX_ENUM_CONSTANTS 1023
#define C_MAX_NESTED_STRUCTS 63
#define C_MAX_PUNCTUATOR_LENGTH 3

#endif
