add_subdirectory('lvalue')
add_subdirectory('assignment')
add_subdirectory('array-to-pointer')
add_subdirectory('function-to-pointer')
add_subdirectory('pointer')
add_subdirectory('integer-promotion')
add_subdirectory('arithmetic')
add_subdirectory('cmp')
